language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install -r requirements.txt
  - python setup.py install
before_script:
  - cp -r test build/lib
script:
  - nosetests --where=build/lib
notifications:
  email: false

